name: Auto Delete Vercel Project

on:
  workflow_dispatch: # 手動実行用トリガー（テスト用）

jobs:
  delete-vercel-project:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Project from Vercel
        run: |
          curl -X DELETE "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"